export const ENV_SECRET_KEYS = [
  "BETTER_AUTH_SECRET",
  "DATABASE_URL",
  "DISCORD_OAUTH_ID",
  "DISCORD_OAUTH_SECRET",
  "GITHUB_OAUTH_ID",
  "GITHUB_OAUTH_SECRET",
  "GOOGLE_OAUTH_ID",
  "GOOGLE_OAUTH_SECRET",
  "SENTRY_AUTH_TOKEN",
  "VERCEL_BLOB_RW_TOKEN",
] as const;
